// backup screen will be generated by previous step; placeholder to ensure router compiles.
import 'package:flutter/material.dart';
class BackupScreen extends StatelessWidget { const BackupScreen({super.key}); @override Widget build(BuildContext context) => const Center(child: Text('Backup')); }